--1
SET NOCOUNT ON
IF EXISTS (SELECT * FROM  SYS.OBJECTS  -- таблица TAB есть?
WHERE OBJECT_ID = OBJECT_ID(N'DBO.TAB') )	            
DROP TABLE TAB;           
DECLARE @C INT, @FLAG CHAR = 'C'; -- commit или rollback?
SET IMPLICIT_TRANSACTIONS  ON -- включ. режим неявной транзакции
CREATE TABLE TAB(K INT); -- начало транзакции 
INSERT TAB VALUES (1), (2), (3);
SET @C = (SELECT COUNT(*) FROM TAB);
PRINT 'Количество строк в таблице TAB: ' + CAST(@C AS VARCHAR(2));
IF @FLAG = 'C' COMMIT; -- завершение транзакции: фиксация 
ELSE ROLLBACK; -- завершение транзакции: откат  
SET IMPLICIT_TRANSACTIONS  OFF -- выключ. режим неявной транзакции
IF EXISTS (SELECT * FROM  SYS.OBJECTS -- таблица TAB есть?
WHERE OBJECT_ID = OBJECT_ID(N'DBO.TAB') )
PRINT 'Таблица TAB существует.';  
ELSE PRINT 'Таблицы TAB нет'
--2
BEGIN TRY
BEGIN TRAN
DELETE AUDITORIUM WHERE AUDITORIUM = '302-4';
INSERT AUDITORIUM VALUES ('207-4', 'ЛБ-К', 15, '207-4');
INSERT AUDITORIUM VALUES ('200-3a', 'ЛК', 180, '300-3a');
COMMIT TRAN;
END TRY
BEGIN CATCH
PRINT 'Ошибка:' + CASE
WHEN ERROR_NUMBER() = 2627 AND PATINDEX('%PK_UNIVER%', ERROR_MESSAGE()) > 0
THEN 'Дублирование аудитории'
ELSE 'Неизвестная ошибка:' + CAST(ERROR_NUMBER() AS VARCHAR(5)) + ERROR_MESSAGE()
END;
IF @@TRANCOUNT > 0 ROLLBACK TRAN;
END CATCH
--3
DECLARE @POINT VARCHAR(32);
BEGIN TRY
BEGIN TRAN
DELETE AUDITORIUM WHERE AUDITORIUM = '302-4';
SET @POINT = 'P1'; SAVE TRAN @POINT;
INSERT AUDITORIUM VALUES ('207-4', 'ЛБ-К', 15, '207-4');
SET @POINT = 'P2'; SAVE TRAN @POINT;
INSERT AUDITORIUM VALUES ('200-3a', 'ЛК', 180, '300-3a');
COMMIT TRAN;
END TRY
BEGIN CATCH
PRINT 'Ошибка:' + CASE
WHEN ERROR_NUMBER() = 2627 AND PATINDEX('%PK_UNIVER%', ERROR_MESSAGE()) > 0
THEN 'Дублирование аудитории'
ELSE 'Неизвестная ошибка:' + CAST(ERROR_NUMBER() AS VARCHAR(5)) + ERROR_MESSAGE()
END;
IF @@TRANCOUNT > 0 
BEGIN
PRINT 'Контрольная точка: ' + @POINT;
ROLLBACK TRAN @POINT;
COMMIT TRAN;
END;
END CATCH
--4
--A--
SET TRAN ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRAN
SELECT COUNT(*) FROM AUDITORIUM;
--T1--
--T2--
SELECT COUNT(*) FROM AUDITORIUM; 
COMMIT TRAN;
--5
------------------- НЕПОДТВЕРЖДЁННОЕ ЧТЕНИЕ
 INSERT INTO AUDITORIUM VALUES ('423-1', 'ЛК', 60, '423-1');
--A--
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT COUNT(*) FROM AUDITORIUM;
--T1--
SELECT COUNT(*) FROM AUDITORIUM;
--T2--
SELECT COUNT(*) FROM AUDITORIUM;
COMMIT TRAN;
----------------------- НЕПОВТОРЯЮШЕЕСЯ ЧТЕНИЕ
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT COUNT(*) FROM AUDITORIUM;
----------------------------
SELECT COUNT(*) FROM AUDITORIUM;
COMMIT TRAN;
---------------------------
--6
------ НЕ ДОПУСКАЕТ НЕПОВТОРЯЮЩЕЕСЯ ЧТЕНИЕ зависвовторой
INSERT INTO AUDITORIUM VALUES ('444-4', 'ЛК', 60, '444-4');

--A--
SET TRAN ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN
SELECT COUNT(*) FROM AUDITORIUM;
--T1--
--T2--
COMMIT TRAN;
------------------------------ ДОПУСКАЕТ ПРОБЛЕМУ ФАНТОМНЫХ ЗАПИСЕЙ
INSERT INTO AUDITORIUM VALUES ('444-4', 'ЛК', 60, '444-4');
-----------------------------
SET TRAN ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN
SELECT COUNT(*) FROM AUDITORIUM;
------------------------------
SELECT COUNT(*) FROM AUDITORIUM;
COMMIT TRAN;
------------------------------
--7 НЕ ДОПУСКАЕТ ПРОБЛЕМУ ФАНТОМНЫХ ЗАПИСЕЙ
--A--
SET TRAN ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN
SELECT COUNT(*) FROM AUDITORIUM;
--T1--
--T2--
COMMIT TRAN;
--8
BEGIN TRAN
INSERT AUDITORIUM_TYPE VALUES('НК', 'Научный кабинет');
BEGIN TRAN
UPDATE AUDITORIUM SET AUDITORIUM_TYPE = 'НК' WHERE AUDITORIUM = '325-1';
COMMIT;
IF @@TRANCOUNT > 0 ROLLBACK;
SELECT 
(SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'ЛК') 'Аудитории',
(SELECT COUNT(*) FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE = 'НК') 'Научные кабинеты';