--Все кафедры на факультете ЛХФ и удалить кафедру на Л
DECLARE @PULP CHAR(10), @ALLP CHAR(300) = '';
DECLARE CURSORPULP CURSOR LOCAL DYNAMIC FOR
SELECT PULPIT FROM PULPIT WHERE FACULTY = 'ЛХФ' FOR UPDATE;

OPEN CURSORPULP;

FETCH CURSORPULP INTO @PULP;
--DELETE PULPIT WHERE PULPIT LIKE 'Л%';
PRINT 'Кафедры на факультете ЛХФ';
WHILE @@FETCH_STATUS = 0
BEGIN
SET @ALLP = RTRIM(@PULP) + ', ' + @ALLP;
FETCH CURSORPULP INTO @PULP;
END;
PRINT @ALLP;

CLOSE CURSORPULP;