SET TRAN ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN
DELETE AUDITORIUM WHERE AUDITORIUM_TYPE = 'À - ';
INSERT AUDITORIUM VALUES ('325-1', 'À ', 20, '325-1');
UPDATE AUDITORIUM SET AUDITORIUM_TYPE = 'À - ' WHERE AUDITORIUM = '325-1';
SELECT AUDITORIUM_TYPE FROM AUDITORIUM WHERE AUDITORIUM = '325-1'
--T1--
SELECT AUDITORIUM_TYPE FROM AUDITORIUM WHERE AUDITORIUM = '325-1'
--T2--
COMMIT;