BEGIN TRAN
INSERT AUDITORIUM_TYPE VALUES('НК', 'Научный кабинет');
BEGIN TRAN
UPDATE AUDITORIUM SET AUDITORIUM_TYPE = 'НК' WHERE AUDITORIUM = '325-1';
COMMIT;
IF @@TRANCOUNT > 0 ROLLBACK;
SELECT 
(SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'ЛК') 'Аудитории',
(SELECT COUNT(*) FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE = 'НК') 'Научные кабинеты'BEGIN TRAN
INSERT AUDITORIUM_TYPE VALUES('НК', 'Научный кабинет');
BEGIN TRAN
UPDATE AUDITORIUM SET AUDITORIUM_TYPE = 'НК' WHERE AUDITORIUM = '325-1';
COMMIT;
IF @@TRANCOUNT > 0 ROLLBACK;
SELECT 
(SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'ЛК') 'Аудитории',
(SELECT COUNT(*) FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE = 'НК') 'Научные кабинеты'