Select AUDITORIUM.AUDITORIUM_NAME AS [Название аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME As [Имя типа аудитории], AUDITORIUM.AUDITORIUM_CAPACITY As [Вместимость]
From AUDITORIUM Inner Join AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
Where AUDITORIUM.AUDITORIUM_TYPE = 'Лк' For xml Auto,
Root('Список_аудиторий'), elements;