Select FACULTY.FACULTY As [‘акультет], GROUPS.PROFESSION As [—пециальность], GROUPS.IDGROUP,
round (avg(cast(PROGRESS.NOTE as float (4))),2) [—редн€€ оценка]
From FACULTY Inner Join GROUPS
On FACULTY.FACULTY = GROUPS.FACULTY 
Inner Join STUDENT
On GROUPS.IDGROUP = STUDENT.IDGROUP
Inner Join PROGRESS
On PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
Group by FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.IDGROUP
Order by [—редн€€ оценка] desc

Select FACULTY.FACULTY As [‘акультет], GROUPS.PROFESSION As [—пециальность], GROUPS.IDGROUP As[√руппа],PROGRESS.SUBJECT As [ƒисциплина],
round (avg(cast(PROGRESS.NOTE as float (4))),2) [—редн€€ оценка]
From FACULTY Inner Join GROUPS
On FACULTY.FACULTY = GROUPS.FACULTY 
Inner Join STUDENT
On GROUPS.IDGROUP = STUDENT.IDGROUP
Inner Join PROGRESS
On PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
Where (PROGRESS.SUBJECT = '—уЅд' or PROGRESS.SUBJECT = 'ќјиѕ')
Group by FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.IDGROUP, PROGRESS.SUBJECT
Order by [—редн€€ оценка] desc