SELECT PROFESSION [Специальность], SUBJECT [Дисциплина],
ROUND(AVG(CAST(p.NOTE AS FLOAT(4))), 2) [Средняя оценка]
FROM GROUPS g INNER JOIN STUDENT s
ON g.IDGROUP = s.IDGROUP
INNER JOIN PROGRESS p
ON s.IDSTUDENT = p.IDSTUDENT 
WHERE g.FACULTY LIKE 'ИТ'
GROUP BY g.PROFESSION, p.SUBJECT, p.NOTE
UNION
SELECT PROFESSION [Специальность], SUBJECT [Дисциплина],
ROUND(AVG(CAST(p.NOTE AS FLOAT(4))), 2) [Средняя оценка]
FROM GROUPS g INNER JOIN STUDENT s
ON g.IDGROUP = s.IDGROUP
INNER JOIN PROGRESS p
ON s.IDSTUDENT = p.IDSTUDENT 
WHERE g.FACULTY LIKE 'ХТиТ'
GROUP BY g.PROFESSION, p.SUBJECT, p.NOTE

SELECT PROFESSION [Специальность], SUBJECT [Дисциплина],
ROUND(AVG(CAST(p.NOTE AS FLOAT(4))), 2) [Средняя оценка]
FROM GROUPS g INNER JOIN STUDENT s
ON g.IDGROUP = s.IDGROUP
INNER JOIN PROGRESS p
ON s.IDSTUDENT = p.IDSTUDENT 
WHERE g.FACULTY LIKE 'ИТ'
GROUP BY g.PROFESSION, p.SUBJECT, p.NOTE
UNION ALL
SELECT PROFESSION [Специальность], SUBJECT [Дисциплина],
ROUND(AVG(CAST(p.NOTE AS FLOAT(4))), 2) [Средняя оценка]
FROM GROUPS g INNER JOIN STUDENT s
ON g.IDGROUP = s.IDGROUP
INNER JOIN PROGRESS p
ON s.IDSTUDENT = p.IDSTUDENT 
WHERE g.FACULTY LIKE 'ХТиТ'
GROUP BY g.PROFESSION, p.SUBJECT, p.NOTE



