GO
CREATE TRIGGER TR_TEACHER_DEL1 ON TEACHER AFTER DELETE
AS 
DECLARE @A1 CHAR(10), @A2 VARCHAR(100), @A3 CHAR(1), @A4 CHAR (20), @ALL VARCHAR(300);
BEGIN
SET @A1 = (SELECT TEACHER FROM DELETED);
SET @A2 = (SELECT TEACHER_NAME FROM DELETED);
SET @A3 = (SELECT GENDER FROM DELETED);
SET @A4 = (SELECT PULPIT FROM DELETED);
SET @ALL = CAST(@A1 AS VARCHAR(10)) + ' ' + CAST(@A2 AS VARCHAR(100)) + ' ' 
+ CAST(@A3 AS VARCHAR(1)) + ' ' + CAST(@A4 AS VARCHAR(20)) + ' ';
INSERT INTO TR_AUDIT(STMT, TRNAME, CC) VALUES('DEL', 'TR_TEACHER_DEL1', @ALL);
END;
RETURN;
GO
CREATE TRIGGER TR_TEACHER_DEL2 ON TEACHER AFTER DELETE
AS 
DECLARE @A1 CHAR(10), @A2 VARCHAR(100), @A3 CHAR(1), @A4 CHAR (20), @ALL VARCHAR(300);
BEGIN
SET @A1 = (SELECT TEACHER FROM DELETED);
SET @A2 = (SELECT TEACHER_NAME FROM DELETED);
SET @A3 = (SELECT GENDER FROM DELETED);
SET @A4 = (SELECT PULPIT FROM DELETED);
SET @ALL = CAST(@A1 AS VARCHAR(10)) + ' ' + CAST(@A2 AS VARCHAR(100)) + ' ' 
+ CAST(@A3 AS VARCHAR(1)) + ' ' + CAST(@A4 AS VARCHAR(20)) + ' ';
INSERT INTO TR_AUDIT(STMT, TRNAME, CC) VALUES('DEL', 'TR_TEACHER_DEL2', @ALL);
END;
RETURN;
GO
CREATE TRIGGER TR_TEACHER_DEL3 ON TEACHER AFTER DELETE
AS 
DECLARE @A1 CHAR(10), @A2 VARCHAR(100), @A3 CHAR(1), @A4 CHAR (20), @ALL VARCHAR(300);
BEGIN
SET @A1 = (SELECT TEACHER FROM DELETED);
SET @A2 = (SELECT TEACHER_NAME FROM DELETED);
SET @A3 = (SELECT GENDER FROM DELETED);
SET @A4 = (SELECT PULPIT FROM DELETED);
SET @ALL = CAST(@A1 AS VARCHAR(10)) + ' ' + CAST(@A2 AS VARCHAR(100)) + ' ' 
+ CAST(@A3 AS VARCHAR(1)) + ' ' + CAST(@A4 AS VARCHAR(20)) + ' ';
INSERT INTO TR_AUDIT(STMT, TRNAME, CC) VALUES('DEL', 'TR_TEACHER_DEL3', @ALL);
END;
RETURN;

SELECT T.NAME, E.TYPE_DESC 
FROM SYS.TRIGGERS  T JOIN  SYS.TRIGGER_EVENTS E  
ON T.OBJECT_ID = E.OBJECT_ID  
WHERE OBJECT_NAME(T.PARENT_ID) = 'TEACHER' AND 
E.TYPE_DESC = 'DELETE' ;  
EXEC  SP_SETTRIGGERORDER @TRIGGERNAME = 'TR_TEACHER_DEL3', 
@ORDER = 'FIRST', @STMTTYPE = 'DELETE';
EXEC  SP_SETTRIGGERORDER @TRIGGERNAME = 'TR_TEACHER_DEL2', 
@ORDER = 'LAST', @STMTTYPE = 'DELETE';

Delete From TEACHER Where TEACHER = ' –œ“1'
Select * From TR_AUDIT;

Drop  TRIGGER TR_TEACHER_DEL1;
Drop  TRIGGER TR_TEACHER_DEL2;
Drop  TRIGGER TR_TEACHER_DEL3;
