Select AUDITORIUM_TYPE As [Тип аудидории], AUDITORIUM_CAPACITY As [Вместимость аудитории]
From AUDITORIUM a
Where AUDITORIUM_TYPE = (Select Top(1) AUDITORIUM_TYPE From AUDITORIUM aa
Where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE Order by AUDITORIUM_CAPACITY Desc)
Order by AUDITORIUM_CAPACITY Desc

