--выв средний бал
GO
CREATE PROCEDURE SUBPROC @SUB VARCHAR(20)
AS
BEGIN
DECLARE @AVG INT = (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = @SUB)
PRINT @AVG
RETURN @AVG;
END;
GO
DECLARE @SUB VARCHAR(20);
EXEC SUBPROC @SUB = 'КГ'

DROP PROCEDURE SUBPROC;